### ISSUE TITLE
Feature: User can view main page

### ISSUE THREAD

**Issue by sallysujilee** [sallysujilee/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can view main page

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Being on the main page allows the user to understand that the site can be used as a tool for the user to utilize to enhance their game strategy and/or make their gameplay into a fun time.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-04-25 at 11 12 51 AM](https://user-images.githubusercontent.com/75781137/234365354-96474e6c-6702-492c-9e41-7cb6b6fe66c0.png)

![Screenshot 2023-04-25 at 11 13 43 AM](https://user-images.githubusercontent.com/75781137/234365529-c66ecf1f-cbe0-4084-8d6f-8b4cbda29e74.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Research how to implement API into site
- [ ] Download image files into computer
	- [ ] Create folder for image files
	- [ ] Insert image files into directory for images
- [ ] Red underline on buttons when hovered
- [ ] Make the Valorant logo clickable (will link user back to main page)
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
