### ISSUE TITLE
Feature: User can view a list of gun choices

### ISSUE THREAD

**Issue by sallysujilee** [sallysujilee/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can view the list of gun choices.
User can add a gun of their choice to their favorites list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to see a visual of all the weapons used within the game. From here, user can view the specs of each weapon and save to their favorites list, if they wish.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [ ] Have the display show the image of the weapon and the gun name
- [ ] Add a star shaped button to the top right of the display image
        - [ ] Button can be clicked to fill in color of star to indicate action
        - [ ] Button can be clicked again to remove action
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
